---
name: "Build HAQQ release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the version"
        required: true
        default: "v1.7.0"
  pull_request:
    branches:
      - "master"

permissions:
  contents: "write"

env:
  HAQQ_VERSION: "${{ inputs.version || 'v1.7.0' }}"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest-l"
    steps:
      - id: "setup-go"
        name: "Setup Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.21"

      - id: "setup-dependencies"
        name: "Install required system packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential curl git

      - id: "clone-pipeline"
        name: "Clone pipeline"
        uses: "actions/checkout@v4"
        with:
          path: "pipeline"

      - id: "clone"
        name: "Clone HAQQ source"
        uses: "actions/checkout@v4"
        with:
          repository: "haqq-network/haqq"
          fetch-tags: true
          path: "haqq"
          ref: "refs/tags/${{ env.HAQQ_VERSION }}"
          submodules: true

      - id: "apply-patches"
        name: "Apply patches"
        run: |
          set -euo pipefail
          shopt -s nullglob

          cd "${GITHUB_WORKSPACE}/haqq"
          git am --3way "${GITHUB_WORKSPACE}/pipeline/patches"/*.patch

      - id: "build"
        name: "Build haqqd binary"
        run: |
          cd haqq

          make LEDGER_ENABLED=false build

          # Smoke test
          ldd ./build/haqqd || :
          ./build/haqqd version --long

      - id: "upload-artifact"
        name: "Save binary to workspace"
        uses: "actions/upload-artifact@v3"
        with:
          name: "haqq"
          path: "haqq/build/haqqd"
          if-no-files-found: "error"
          retention-days: 1

  publish:
    name: "Publish"
    needs: "build"
    runs-on: "ubuntu-latest"
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    steps:
      - id: "download-artifact"
        name: "Download binary from workspace"
        uses: "actions/download-artifact@v3"
        with:
          name: "haqq"
          path: "binaries"

      - id: "publish"
        name: "Publish Github release"
        uses: "softprops/action-gh-release@v1"
        with:
          body: |
            For changes, see here: https://github.com/haqq-network/haqq/releases/tag/${{ env.HAQQ_VERSION }}
          files: |
            binaries/haqqd
          tag_name: "${{ env.HAQQ_VERSION }}"
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
